.PHONY: clean All

All:
	@echo "----------Building project:[ OOPLProject - Debug ]----------"
	@"$(MAKE)" -f  "OOPLProject.mk"
clean:
	@echo "----------Cleaning project:[ OOPLProject - Debug ]----------"
	@"$(MAKE)" -f  "OOPLProject.mk" clean
